# Generated by Django 4.0.4 on 2022-07-26 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.order')),
            ],
        ),
    ]
