# Generated by Django 4.0.4 on 2022-07-26 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
    ]
