# Generated by Django 4.0.4 on 2022-07-28 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sale_created_at_sale_updated_at_stock_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Fechado', 'Fechado'), ('Cancelado', 'Cancelado')], default='Aberto', max_length=50)),
                ('total_parcela', models.CharField(blank=True, max_length=255, null=True)),
                ('desconto', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('tipo_frete', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_frete', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sale')),
            ],
        ),
    ]
