# Generated by Django 4.0.4 on 2022-07-28 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=50)),
                ('forma_pagamento', models.CharField(max_length=255)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('parcela', models.CharField(blank=True, max_length=255, null=True)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faturamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.billing')),
            ],
        ),
    ]
