# Generated by Django 4.0.4 on 2022-06-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to='users/pictures/%Y/%m/%d'),
        ),
    ]
