# Generated by Django 4.0.4 on 2022-07-16 19:19

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to=apps.users.models.path_and_rename),
        ),
    ]
