# Generated by Django 4.0.4 on 2022-09-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'required': 'O e-mail é obrigatório'}, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(error_messages={'max_length': 'O nome deve ter menos de 50 caracteres.', 'required': 'Informe seu nome'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(error_messages={'max_length': 'O sobrenome deve ter menos de 50 caracteres.', 'required': 'Informe seu sobrenome'}, max_length=50),
        ),
    ]
